[package]
name = "limnus-system"
version = "0.0.18"
edition = "2024"
repository = "https://github.com/swamp/limnus"
license = "MIT"
categories = ["game-development"]
description = "Limnus systems"


[dependencies]
limnus-system-state = {path = "../system-state", version = "0.0.18" }
