[package]
name = "limnus-window-runner"
version = "0.0.17"
edition = "2021"
repository = "https://github.com/swamp/limnus"
license = "MIT"
categories = ["game-development"]
description = "winit runner for limnus-app"

[dependencies]
limnus-app = { path = "../app", version = "0.0.17" }
limnus-window = { path = "../window", version = "0.0.17" }
limnus-wgpu-window = { path = "../wgpu-window", version = "0.0.17" }
future-runner = "0.0.1"
limnus-basic-input = { path = "../basic-input", version = "0.0.17" }
limnus-screen = { path = "../screen", version = "0.0.17" }

winit = "0.30.8"
int_math = "0.0.2"
tracing = "0.1.40"
console_error_panic_hook = "0.1.7"
