[package]
name = "limnus-system-state"
version = "0.0.18"
edition = "2024"
repository = "https://github.com/swamp/limnus"
license = "MIT"
categories = ["game-development"]
description = "Keeps the state that is provided to systems"


[dependencies]
limnus-resource = { path = "../resource", version = "0.0.18" }
limnus-message = { path = "../message", version = "0.0.18" }

limnus-local-resource = { path = "../local-resource", version = "0.0.18" }
