[package]
name = "limnus-gamepad-gilrs"
version = "0.0.10"
edition = "2021"
license = "MIT"
description = "Small wrapper around gilrs to provide gamepad abstraction"
repository = "https://github.com/swamp/limnus"
categories = ["game-development"]
keywords = ["game", "input"]

[dependencies]
tracing = "0.1.41"
gilrs = "0.11.0"

limnus-gamepad = { path = "../gamepad", version = "0.0.10" }
limnus-app = { path = "../app", version = "0.0.10" }
limnus-system-params = { path = "../system-params", version = "0.0.10" }
limnus-local-resource = { path = "../local-resource", version = "0.0.10" }
limnus-system-runner = { path = "../system-runner", version = "0.0.10" }

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace"] }
limnus-log = { path = "../log", version = "0.0.10" }
