[package]
name = "limnus-wgpu-window"
version = "0.0.15"
edition = "2021"
license = "MIT"
description = "creating and managing a window with rendering surfaces using winit and wgpu"
repository = "https://github.com/swamp/limnus"
categories = ["game-development"]
keywords = ["game", "render", "sprites"]

[dependencies]
wgpu = "23.0.0"
winit = "0.30.8"
limnus-app = { path = "../app", version = "0.0.15" }
limnus-screen = { path = "../screen", version = "0.0.15" }
tracing = "0.1.40"
limnus-system-params = { path = "../system-params", version = "0.0.15" }
limnus-local-resource = { path = "../local-resource", version = "0.0.15" }
limnus-default-stages = { path = "../default-stages", version = "0.0.15" }
