[package]
name = "limnus-wgpu-window"
version = "0.0.12"
edition = "2021"
license = "MIT"
description = "creating and managing a window with rendering surfaces using winit and wgpu"
repository = "https://github.com/swamp/limnus"
categories = ["game-development"]
keywords = ["game", "render", "sprites"]

[dependencies]
wgpu = "23.0.0"
winit = "0.30.5"
limnus-app = { path = "../app", version = "0.0.12" }
limnus-screen = { path = "../screen", version = "0.0.12" }
tracing = "0.1.40"
limnus-system-params = { path = "../system-params", version = "0.0.12" }
limnus-resource = { path = "../resource", version = "0.0.12" }
limnus-system-runner = { path = "../system-runner", version = "0.0.12" }
