[package]
name = "limnus-default-stages"
version = "0.0.15"
edition = "2021"
license = "MIT"
description = "limnus default stages, `First`, `PreUpdate`, `Update`, `PostUpdate`, etc"

[dependencies]
limnus-stage = { path = "../stage", version = "0.0.15" }
