[package]
name = "limnus-window"
version = "0.0.13"
edition = "2021"
license = "MIT"
description = "Easily create and manage windows across multiple platforms for game applications, leveraging the power of the `winit` library."
repository = "https://github.com/swamp/limnus"
categories = ["game-development"]
keywords = ["game", "window"]

[dependencies]
winit = { version = "0.30.8", features = ["rwh_05"] }
limnus-log = { path = "../log", version = "0.0.13" }

# WASM
wasm-bindgen = "0.2.99"
web-sys = { version = "0.3.76", features = ["Document", "Element", "HtmlCanvasElement"] }
tracing = "0.1.40"

[dev-dependencies]
env_logger = "0.11.5"
