[package]
name = "limnus-examples"
version = "0.0.10"
edition = "2021"

[[bin]]
name = "gamepad_tester"
path = "src/bin/gamepad_tester.rs"

[dependencies]

limnus-app = { path = "../app", version = "0.0.10" }
limnus-system-params = { path = "../system-params", version = "0.0.10" }
limnus-local-resource = { path = "../local-resource", version = "0.0.10" }
limnus-system-runner = { path = "../system-runner", version = "0.0.10" }
limnus-gamepad = { path = "../gamepad", version = "0.0.10" }
limnus-gamepad-gilrs = { path = "../gamepad-gilrs", version = "0.0.10" }
limnus-log = { path = "../log", version = "0.0.10" }
tracing = "0.1.41"
