[package]
name = "limnus-examples"
version = "0.0.11"
edition = "2021"
license = "MIT"
description = "examples for the limnus game engine"
repository = "https://github.com/swamp/limnus"
categories = ["game-development"]
keywords = ["game", "examples"]

[[bin]]
name = "gamepad_tester"
path = "src/bin/gamepad_tester.rs"

[dependencies]

limnus-app = { path = "../app", version = "0.0.11" }
limnus-system-params = { path = "../system-params", version = "0.0.11" }
limnus-local-resource = { path = "../local-resource", version = "0.0.11" }
limnus-system-runner = { path = "../system-runner", version = "0.0.11" }
limnus-gamepad = { path = "../gamepad", version = "0.0.11" }
limnus-gamepad-gilrs = { path = "../gamepad-gilrs", version = "0.0.11" }
limnus-log = { path = "../log", version = "0.0.11" }
tracing = "0.1.41"
limnus-assets-loader = { path = "../assets-loader", version = "0.0.11" }
limnus-loader = { path = "../loader", version = "0.0.11" }
limnus = { path = "../limnus", version = "0.0.11" }
