[package]
name = "limnus-stage"
version = "0.0.15"
edition = "2021"

[dependencies]
limnus-system = { path = "../system", version = "0.0.15" }
limnus-system-state = { path = "../system-state", version = "0.0.15" }
limnus-local-resource = { path = "../local-resource", version = "0.0.15" }
