[package]
name = "limnus"
version = "0.0.11"
edition = "2021"
license = "MIT"
description = "Limnus game engine core"
repository = "https://github.com/swamp/limnus"
categories = ["game-development"]
keywords = ["game", "engine"]

[dependencies]
limnus-app = { path = "../app", version = "0.0.11" }
limnus-asset-id = { path = "../asset-id", version = "0.0.11" }
limnus-asset-registry = { path = "../asset-registry", version = "0.0.11" }
limnus-assets = { path = "../assets", version = "0.0.11" }
limnus-assets-loader = { path = "../assets-loader", version = "0.0.11" }
limnus-basic-input = { path = "../basic-input", version = "0.0.11" }
limnus-gamepad = { path = "../gamepad", version = "0.0.11" }
limnus-gamepad-gilrs = { path = "../gamepad-gilrs", version = "0.0.11" }
limnus-window-runner = { path = "../window-runner", version = "0.0.11" }
limnus-wgpu-window = { path = "../wgpu-window", version = "0.0.11" }
limnus-log = { path = "../log", version = "0.0.11" }
limnus-wgpu-math = { path = "../wgpu-math", version = "0.0.11" }
limnus-system-params = { path = "../system-params", version = "0.0.11" }
limnus-screen = { path = "../screen", version = "0.0.11" }
limnus-macros = { path = "../macros", version = "0.0.11" }
limnus-window = { path = "../window", version = "0.0.11" }
limnus-system-runner = { path = "../system-runner", version = "0.0.11" }
limnus-resource = { path = "../resource", version = "0.0.11" }
limnus-local-resource = { path = "../local-resource", version = "0.0.11" }
limnus-message = { path = "../message", version = "0.0.11" }
limnus-loader = { path = "../loader", version = "0.0.11" }

limnus-audio-device = { path = "../audio-device", version = "0.0.11", optional = true }
limnus-audio-sample = { path = "../audio-sample", version = "0.0.11", optional = true }
limnus-audio-stream = { path = "../audio-stream", version = "0.0.11", optional = true }
limnus-audio-mixer = { path = "../audio-mixer", version = "0.0.11", optional = true }


[features]
default = ["audio"]
audio = ["limnus-audio-device", "limnus-audio-sample", "limnus-audio-mixer", "limnus-audio-stream"]
